//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using Newtonsoft.Json;using System.Runtime.Serialization; using interfaces;
    using System.Collections.Generic;
    
    public partial class tpagtransaccion :IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tpagtransaccion()
        {
            this.tpagmovimiento = new HashSet<tpagmovimiento>();
        }
    
        public long ctransaccion { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> debito { get; set; }
        public string abr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tpagmovimiento> tpagmovimiento { get; set; }
    }
}
