//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using Newtonsoft.Json;using System.Runtime.Serialization; using interfaces;
    using System.Collections.Generic;
    
    public partial class tpagmovimiento :IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cmovimiento { get; set; }
        public Nullable<long> ctransaccion { get; set; }
        public Nullable<long> cuentaorg { get; set; }
        public Nullable<long> cuentades { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> debito { get; set; }
        public string terminal { get; set; }
        public Nullable<System.DateTime> fproceso { get; set; }
        public string descripcion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpagcuenta tpagcuenta { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpagcuenta tpagcuenta1 { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpagtransaccion tpagtransaccion { get; set; }
    }
}
